### ISSUE TITLE
1.06 Decimals and Data Import

### ISSUE THREAD

**Issue by BurgersMcFly** [vawser/Yapped-Rune-Bear#18]
Unfortunately decimals are still messing up with Yapped's values.

![soffice bin_CdWFKKbJUS](https://user-images.githubusercontent.com/26502050/159948498-0ab9ab1d-2e9a-43e3-b85a-0331226e54b3.png)
![Yapped_w7fSpqCZBK](https://user-images.githubusercontent.com/26502050/159948518-9b802830-d082-4965-9e3d-03a8e03b79fa.png)

Data Import is fast af! Gj

But need to click on a different Row for the values to actually update. Is cool, just thought of letting you know, might be a bug I don't know lol D:

**Comment by vawser** [comment]
I've tried to replicate this issue and the import was fine for me, the 1.5 retained the correct value. 

However my test is directly with the CSV file without importing it into a spreadsheet application, which may be why it is being messed up for you, since spreadsheet software can make assumptions when it comes to CSV files, and so saving it may be causing the "." to be dropped in some way.

**Comment by BurgersMcFly** [comment]
Like just edit it in something like notepad ++?

Will try again when back home and imma let you know.

**Comment by vawser** [comment]
Oh. I see the issue here. I don't intend to support other decimal locales. Yapped should export it as 1.5, and then it is up to you to make sure the spreadsheet doesn't change it to 1,5.

**Comment by BurgersMcFly** [comment]
K mate, thanks a lot. 

Does that mean that Yapped defaults to "." for decimals no matter where you live?

**Comment by vawser** [comment]
It should now the InvariantCulture is set. However spreadsheet software will convert it to your locale, which explains people's issues if they use it to edit the CSV file.

**Comment by BurgersMcFly** [comment]
Awesome, will make sure to let them know. Thanks again.
