### ISSUE TITLE
Yapped is corrupting regulation.bin

### ISSUE THREAD

**Issue by specopsbarton** [vawser/Yapped-Rune-Bear#34]
Hello, today I noticed a weird bug caused by yapped after saving.
Even on pure regulation.bin file no matter which value I change, when in game Elden Ring gold sign used to summon npcs to fight bosses disappear, while on pure regulation.bin it is visible normally. This bug happens in my mod, but to be sure I downloaded and tested another mod and the same bug happens there. 
Please help.

Version of yapped: Yapped-Rune-Bear-1_09
Elden Ring version: 1.03.2 Calibrated 1.03.3
Link to my mod: https://www.nexusmods.com/eldenring/mods/159?tab=description

**Comment by BurgersMcFly** [comment]
Try doing Settings->Params to ignore during save and put SignPuddleParam on a clean regulation.bin file. 
Not home atm to test it myself unfortunately.
Not sure if this param is responsible for NPC summon signs but worth a try.

**Comment by specopsbarton** [comment]
I tested latest update and unfortunately still this bug happens :/

**Comment by BurgersMcFly** [comment]
Not fixed with version 1.10.
How to replicate:

Started a new game and went straight to  Margit's boss fight.
Summon sign before the fight is there while using a clean regulation.bin file.

![eldenring_p2zulk2NrC](https://user-images.githubusercontent.com/26502050/162071695-63f7df81-0ea7-48f5-8632-cc5bb50584f0.jpg)


Summon sign gone when opening and saving the regulation.bin file through Yapped. No modifications done.


![eldenring_qClHXXA1b5](https://user-images.githubusercontent.com/26502050/162071731-635028d2-4a54-455a-8568-83fbd36b179d.jpg)

**Comment by BurgersMcFly** [comment]
Fixed by doing Settings->Param to ignore during save and added PlayRegionParam.

**Comment by specopsbarton** [comment]
I tested it and it works. There will be version that will fix this bug in current mods?

**Comment by vawser** [comment]
I've adjusted the layouts for the PlayRegionParam. Seems like there was a misalignment with the booleans. You will need to import the old data from the vanilla PlayRegionParam to fix the issue, but it should no longer wipe the boolean data. 

It should look similar to this when you import the vanilla data.
![image](https://user-images.githubusercontent.com/4229194/162180484-d612911f-b863-43ae-b946-bb88527e28ad.png)

**Comment by BurgersMcFly** [comment]
Fixed. GJ

**Comment by specopsbarton** [comment]
It works now thanks.
